"""initial

Revision ID: d4dfdc646da1
Revises: 
Create Date: 2026-01-06 21:27:15.129689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4dfdc646da1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('series_ticker', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('mutually_exclusive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('markets',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('event_ticker', sa.String(), nullable=False),
    sa.Column('series_ticker', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiration_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_ticker'], ['events.ticker'], ),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index('idx_markets_event', 'markets', ['event_ticker'], unique=False)
    op.create_index('idx_markets_expiration', 'markets', ['expiration_time'], unique=False)
    op.create_index('idx_markets_status', 'markets', ['status'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('yes_bid', sa.Integer(), nullable=False),
    sa.Column('yes_ask', sa.Integer(), nullable=False),
    sa.Column('no_bid', sa.Integer(), nullable=False),
    sa.Column('no_ask', sa.Integer(), nullable=False),
    sa.Column('last_price', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('volume_24h', sa.Integer(), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('liquidity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['markets.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_ticker_time', 'price_snapshots', ['ticker', 'snapshot_time'], unique=False)
    op.create_index('idx_snapshots_time', 'price_snapshots', ['snapshot_time'], unique=False)
    op.create_table('settlements',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('event_ticker', sa.String(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('final_yes_price', sa.Integer(), nullable=True),
    sa.Column('final_no_price', sa.Integer(), nullable=True),
    sa.Column('yes_payout', sa.Integer(), nullable=True),
    sa.Column('no_payout', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['markets.ticker'], ),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlements')
    op.drop_index('idx_snapshots_time', table_name='price_snapshots')
    op.drop_index('idx_snapshots_ticker_time', table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index('idx_markets_status', table_name='markets')
    op.drop_index('idx_markets_expiration', table_name='markets')
    op.drop_index('idx_markets_event', table_name='markets')
    op.drop_table('markets')
    op.drop_table('events')
    # ### end Alembic commands ###
